namespace EntityLib.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class seedProducts : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Polo Shirt White','~/admin_area/other_images/United-Colors-of-Benetton-White-Polo-Shirt-0608-0914361-1-pdp_slider_l.jpg','~/admin_area/other_images/United-Colors-of-Benetton-White-Polo-Shirt-0608-0914361-2-pdp_slider_l.jpg','~/admin_area/other_images/United-Colors-of-Benetton-White-Polo-Shirt-0609-0914361-3-pdp_slider_l.jpg','49','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','polo-shirt-white t-shirt',5,4);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Polo Shirt Blue','~/admin_area/other_images/U-S--Polo-Assn--Blue-Polos-0266-586842-1-pdp_slider_l.jpg','~/admin_area/other_images/U-S--Polo-Assn--Blue-Polos-0268-586842-2-pdp_slider_l.jpg','~/admin_area/other_images/U-S--Polo-Assn--Blue-Polos-0271-586842-3-pdp_slider_l.jpg','62','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','polo-shirt-blue t-shirt',5,4);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Polo Shirt Red','~/admin_area/other_images/T-shirt1.jpg','~/admin_area/other_images/T-shirt2.jpg','~/admin_area/other_images/T-shirt3.jpg','45','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','polo-shirt-red t-shirt',5,4);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Polo Shirt Black','~/admin_area/other_images/product.jpg','~/admin_area/other_images/product2.jpg','~/admin_area/other_images/product3.jpg','25','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','polo-shirt-black t-shirt',5,4);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Blue Jacket','~/admin_area/other_images/Next-Denim-Borg-Lined-Western-Jacket-0463-0064553-1-pdp_slider_l.jpg','~/admin_area/other_images/Next-Denim-Borg-Lined-Western-Jacket-0463-0064553-2-pdp_slider_l.jpg','~/admin_area/other_images/Next-Denim-Borg-Lined-Western-Jacket-0465-0064553-3-pdp_slider_l.jpg','169','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','jacket blue',1,4);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','White Jacket','~/admin_area/other_images/Jack---Jones-White-Solid-Denim-Jacket-3115-5549091-1-pdp_slider_l.jpg','~/admin_area/other_images/Jack---Jones-White-Solid-Denim-Jacket-3115-5549091-2-pdp_slider_l.jpg','~/admin_area/other_images/Jack---Jones-White-Solid-Denim-Jacket-3115-5549091-3-pdp_slider_l.jpg','200','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','jacket white',1,4);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Rough Jacket','~/admin_area/other_images/jacket-1.jpg','~/admin_area/other_images/jacket-2.jpg','~/admin_area/other_images/jacket-3.jpg','250','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','jacket rough',1,4);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Jacket Kids Blue','~/admin_area/other_images/Levi-s-Blue-Solid-Denim-Jacket-5953-6506172-1-pdp_slider_l.jpg','~/admin_area/other_images/Levi-s-Blue-Solid-Denim-Jacket-5953-6506172-2-pdp_slider_l.jpg','~/admin_area/other_images/Levi-s-Blue-Solid-Denim-Jacket-5953-6506172-3-pdp_slider_l.jpg','170','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','jacket kids blue',1,6);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Black Blouse Versace Coat','~/admin_area/other_images/Black Blouse Versace Coat1.jpg','~/admin_area/other_images/Black Blouse Versace Coat2.jpg','~/admin_area/other_images/Black Blouse Versace Coat3.jpg','180','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','jacket women blue',4,5);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Fur Coat with Button','~/admin_area/other_images/fur coat with button1.jpg','~/admin_area/other_images/fur coat with button2.jpg','~/admin_area/other_images/fur coat with button3.jpg','210','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','jacket women brown',4,5);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Women Sweater','~/admin_area/other_images/Gini-1.jpg','~/admin_area/other_images/Gini-2.jpg','~/admin_area/other_images/Gini-3.jpg','140','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','sweater women brown',2,5);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Mishmi Navy Blue Medium Satchel Bag','~/admin_area/other_images/Mishmi Navy Blue Medium Satchel Bag 1.jpg','~/admin_area/other_images/Mishmi Navy Blue Medium Satchel Bag 2.jpg','~/admin_area/other_images/Mishmi Navy Blue Medium Satchel Bag 3.jpg','80','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','jacket women brown',2,5);");
            Sql("INSERT INTO Products (Date, ProductTitle,ProductImg1,ProductImg2,ProductImg3,ProductPrice,ProductDesc,ProductKeywords,ProductCategoryId,CategoryId) VALUES('2018-09-17 17:00:00','Mishmi Navy Blue Medium Satchel Bag','~/admin_area/other_images/product-1.jpg','~/admin_area/other_images/product-2.jpg','~/admin_area/other_images/product-3.jpg','70','Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','jacket women brown',2,5);");

        }

        public override void Down()
        {
            Sql("DELETE FROM ProductCategories ;");
        }
    }
}
